Repository wmde/fundraising-app-frontend, pull requests merged in 2024-05, with the labels that each got.

#376 Make mobile navigation menu accessible
  src/components/layout/AppHeader.vue
  src/components/layout/NavigationItems.vue
  src/components/shared/NavigationBurger.vue
  src/components/shared/composables/useDisplaySwitch.ts
  tests/unit/components/layout/AppHeader.spec.ts
Labels: 🦮 accessibility

#372 Improve UoF company budgets
  src/components/pages/UseOfFunds.vue
  src/components/pages/use_of_funds/Company.ts
  src/components/pages/use_of_funds/CompanyBudgets.vue
  src/scss/use_of_funds/CompanyBudgets.scss
Labels: 🦮 accessibility, PM's feedback needed

#348 Set page titles per page
  src/components/App.vue
  src/components/pages/AccessDenied.vue
  src/components/pages/CommentTicker.vue
  src/components/pages/Contact.vue
  src/components/pages/DonationForm.vue
  src/components/pages/Error.vue
  src/components/pages/MembershipForm.vue
  src/components/pages/SystemMessage.vue
  src/components/pages/UpdateAddress.vue
  src/components/pages/UpdateAddressSuccess.vue
  src/pages/access_denied.ts
  src/pages/address_update_success.ts
  src/pages/comment_list.ts
  src/pages/comment_ticker.ts
  src/pages/contact_form.ts
  src/pages/donation_confirmation.ts
  src/pages/donation_form.ts
  src/pages/error.ts
  src/pages/frequent_questions.ts
  src/pages/funds_usage.ts
  src/pages/membership_application.ts
  src/pages/membership_application_confirmation.ts
  src/pages/page_not_found.ts
  src/pages/privacy_protection.ts
  src/pages/static_page.ts
  src/pages/subscription_confirmation.ts
  src/pages/supporters.ts
  src/pages/system_message.ts
  src/pages/update_address.ts
  tests/unit/components/App.spec.ts
Labels: 🦮 accessibility, Sequential Merge

#378 Improve sidebar accessibility
  src/components/App.vue
  src/components/layout/AppSidebar.vue
  src/components/shared/icons/BankIcon.vue
  src/components/shared/icons/InfoIcon.vue
  src/scss/variables.scss
Labels: 🦮 accessibility

#385 Fix -- Main logo graphic for screen reader
  src/components/layout/AppHeader.vue
  src/components/layout/Logo.vue
Labels: 🦮 accessibility, PM's feedback needed

#380 Improve labels on amount field
  src/components/pages/membership_form/Payment.vue
  src/components/shared/form_elements/RadioFormInput.vue
  src/components/shared/form_elements/TextFormInput.vue
  src/components/shared/form_fields/AmountField.vue
Labels: 🦮 accessibility

#346 Add vuejs accessibility plugin
  .eslintrc.js
  package-lock.json
  package.json
  src/components/layout/AppHeader.vue
  src/components/layout/NavigationItems.vue
  src/components/pages/CommentTicker.vue
  src/components/shared/ModalDialogue.vue
  src/components/shared/PaymentBankData.vue
  src/components/shared/form_fields/CityAutocompleteField.vue
  src/components/shared/form_fields/CountryAutocompleteField.vue
  src/components/shared/form_fields/EmailField.vue
  src/components/shared/form_fields/SelectField.vue
  src/components/shared/form_fields/TextField.vue
Labels: 🦮 accessibility

#399 Group dependabot updates
  .github/dependabot.yml
  package-lock.json
  package.json
Labels: Ready for review

#377 Stop labels being read out multiple times
  src/components/pages/Contact.vue
  src/components/pages/donation_confirmation/AddressUpdateForm.vue
  src/components/pages/donation_form/AddressForms.vue
  src/components/pages/donation_form/AddressTypeBasic.vue
  src/components/pages/donation_form/DonationReceipt/AddressFields.vue
  src/components/pages/donation_form/DonationReceipt/NameFields.vue
  src/components/pages/donation_form/Payment.vue
  src/components/pages/donation_form/subpages/AddressPageDonationReceipt.vue
  src/components/pages/membership_form/Address.vue
  src/components/pages/membership_form/AddressType.vue
  src/components/pages/membership_form/MembershipTypeField.vue
  src/components/pages/membership_form/Payment.vue
  src/components/shared/NameFields.vue
  src/components/shared/PostalAddressFields.vue
  src/components/shared/form_fields/CityAutocompleteField.vue
  src/components/shared/form_fields/CountryAutocompleteField.vue
  src/components/shared/form_fields/EmailField.vue
  src/components/shared/form_fields/FormOption.ts
  src/components/shared/form_fields/FormOptions.ts
  src/components/shared/form_fields/IncentivesField.vue
  src/components/shared/form_fields/MailingListField.vue
  src/components/shared/form_fields/RadioField.vue
  src/components/shared/form_fields/SelectField.vue
  tests/unit/components/pages/donation_form/AddressForms.spec.ts
  tests/unit/components/pages/donation_form/AddressTypeBasic.spec.ts
  tests/unit/components/pages/membership_form/Payment.spec.ts
  tests/unit/components/shared/form_elements/CheckboxMultipleFormInput.spec.ts
  tests/unit/components/shared/form_fields/CityAutocompleteField.spec.ts
  tests/unit/components/shared/form_fields/CountryAutocompleteField.spec.ts
  tests/unit/components/shared/form_fields/MailingListField.spec.ts
  tests/unit/components/shared/form_fields/RadioField.spec.ts
  tests/unit/components/shared/form_fields/SelectField.spec.ts
Labels: 🦮 accessibility

#391 Improve labels on membership payment fields
  src/components/pages/membership_form/AddressType.vue
  src/components/pages/membership_form/MembershipTypeField.vue
  src/components/pages/membership_form/Payment.vue
  src/components/pages/membership_form/subpages/PaymentPage.vue
  src/components/shared/PaymentBankData.vue
Labels: 🦮 accessibility
