Repository wmde/fundraising-app-frontend, pull requests merged in 2024-04, with the labels that each got.

#345 UoF Button styling
  src/components/pages/UseOfFunds.vue
  src/scss/use_of_funds/CompanyBudgets.scss
  src/scss/use_of_funds/FundsContent.scss
Labels: accessibility

#349 Fix some eslint a11y issues
  src/components/pages/donation_confirmation/SuccessMessage.vue
  src/components/pages/donation_form/subpages/PaymentPage.vue
  src/components/pages/use_of_funds/FundsDistributionAccordion.vue
  src/components/shared/LocaleSelector.vue
  src/components/shared/PaymentBankData.vue
  src/components/shared/form_fields/AmountField.vue
  src/components/shared/form_fields/CityAutocompleteField.vue
  src/components/shared/form_fields/CountryAutocompleteField.vue
  src/components/shared/form_fields/EmailField.vue
  src/components/shared/form_fields/SelectField.vue
  src/components/shared/form_fields/TextField.vue
Labels: 🦮 accessibility

#357 Lint test files
  package.json
  tests/unit/TestDoubles/FakeDataEncryptor.ts
  tests/unit/TestDoubles/FakeDataPersister.ts
  tests/unit/components/pages/donation_confirmation/AddressAnonymous.spec.ts
  tests/unit/components/pages/donation_confirmation/AddressUpdateForm.spec.ts
  tests/unit/components/pages/donation_form/AddressPage.spec.ts
  tests/unit/components/pages/membership_form/AddressPage.spec.ts
  tests/unit/components/pages/membership_form/MembershipTypeField.spec.ts
  tests/unit/components/pages/membership_form/PaymentPage.spec.ts
  tests/unit/store/address_store.spec.ts
  tests/unit/store/bankdata_store.spec.ts
  tests/unit/store/donation_store.spec.ts
  tests/unit/store/feeValidator.spec.ts
  tests/unit/utils/wait_for_server.spec.ts
Labels: Ready for review

#344 Make amount field more accessible
  src/components/shared/form_elements/RadioFormInput.vue
  src/components/shared/form_elements/TextFormInput.vue
  src/components/shared/form_fields/AmountField.vue
Labels: 🦮 accessibility

#364 Unify font family of UoF button
  src/scss/use_of_funds/FundsContent.scss
Labels: fix, Ready for review

#350 Fix main logo graphic for screen reader
  src/components/layout/AppHeader.vue
Labels: 🦮 accessibility, Ready for review

#356 Improve Radio Field accessibility
  src/components/pages/donation_form/Payment.vue
  src/components/shared/form_elements/RadioFormInput.vue
  src/components/shared/form_fields/AmountField.vue
  src/components/shared/form_fields/RadioField.vue
  src/scss/variables.scss
  tests/unit/components/pages/donation_confirmation/AddressUpdateForm.spec.ts
  tests/unit/components/pages/donation_form/AddressTypeBasic.spec.ts
  tests/unit/components/pages/membership_form/AddressType.spec.ts
  tests/unit/components/pages/membership_form/MembershipTypeField.spec.ts
  tests/unit/components/pages/membership_form/Payment.spec.ts
  tests/unit/components/shared/form_elements/RadioFormInput.spec.ts
  tests/unit/components/shared/form_fields/AmountField.spec.ts
  tests/unit/components/shared/form_fields/RadioField.spec.ts
Labels: rebase needed, 🦮 accessibility
